Repository kiwix/kiwix-js-pwa, pull requests merged in 2025-08, with the labels that each got.

#745 Fix opening and closing of Wikipedia headers
  www/-/mw/skins.vector.styles.css
  www/js/app.js
  www/js/lib/transformStyles.js
Labels: bug/non-critical, regression, user interface

#751 Fix typo in configuration page
  www/index.html
Labels: cleanup

#750 Fix misplaced infoboxes in RTL ZIMs transformed to mobile style
  www/-/mw/skins.vector.styles.css
  www/-/s/style-mobile.css
  www/js/app.js
  www/js/lib/transformStyles.js
Labels: bug/non-critical, user interface

#747 Feat:708 Remove ToC when one or less elements
  www/js/app.js
Labels: enhancement, user interface

#762 Fix remove max page width with ActionParse ZIMs
  www/-/s/style-mobile.css
  www/js/app.js
  www/js/lib/transformStyles.js
Labels: bug/non-critical, regression, user interface

#769 Run nsis and nsis-web builds sequentially
  package.json
Labels: bug, build
